### ISSUE TITLE
Review and update all articles that refer to accounts

### ISSUE THREAD

**Issue by aeden** [aetrion/dnsimple-support#62]
These ones we must update:
- [x] [Close your account](http://support.dnsimple.com/articles/close-account/)
- [x] [Cancel your subscription](http://support.dnsimple.com/articles/cancel-subscription/). See #63 
- [x] [Changing account email](http://support.dnsimple.com/articles/changing-account-email/) (_the last screenshot is obsolete_)
- [x] [Yearly billing](http://support.dnsimple.com/articles/yearly-billing/) (_this needs to be updated to reflect that it's simply a plan change now_). See #64

These we have to add:
- [x] Change subscription plan (_it will be linked from the aforementioned yearly billing article_). See #66 

These ones would benefit from an update but don't have screenshots:
- [x] [Account creation](http://support.dnsimple.com/articles/account-creation/)
- [x] [Account activation](http://support.dnsimple.com/articles/account-activation/)
- [x] [Securing your DNSimple account](http://support.dnsimple.com/articles/account-securing/)

**Comment by aeden** [comment]
@jacegu will create a list of articles that need to be updated.

**Comment by jacegu** [comment]
I updated the description of the issue with the articles that need attention.

**Comment by aeden** [comment]
Here is the branch where work will be done for the multi-account launch: https://github.com/aetrion/dnsimple-support/tree/multi-account

**Comment by jacegu** [comment]
I think I'm done updating the articles. You can start reviewing whenever you want to simpletons!

**Comment by aeden** [comment]
IT IS :ship: ed
